use sakila;

-- 1 List the number of films per category.
SELECT name AS category_name, COUNT(*) AS num_films
FROM category
JOIN film_category using (category_id)
GROUP BY name
 ORDER BY num_films DESC;   

-- 2 Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city, co.country
FROM store s
JOIN address a ON s.address_id = a.address_id
JOIN city c ON a.city_id = c.city_id
JOIN country co ON c.country_id = co.country_id;


-- 3 Calculate the total revenue generated by each store in dollars.
SELECT store.store_id, SUM(payment.amount) AS total_revenue
FROM store
JOIN staff ON store.store_id = staff.store_id
JOIN payment ON staff.staff_id = payment.staff_id
GROUP BY store.store_id;


-- 4 Determine the average running time of films for each category.
SELECT category.name, ROUND(AVG(film.length), 2) AS average_running_time
FROM category
JOIN film_category ON category.category_id = film_category.category_id
JOIN film ON film_category.film_id = film.film_id
GROUP BY category.name;
